sudo: false
language: generic

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version

script:
  - stack build --fast --no-terminal
  - travis_wait 60 sleep 1800 &
  - stack test --fast --no-terminal

cache:
  timeout: 1500
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true
